plugins {
    id 'application'
    id 'checkstyle'
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'koko.Koko'
}

checkstyle {
    toolVersion = '11.0.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
